interface EngineeringIconProps {
  className?: string;
}

// Precomputed gear paths (formerly generated by create_gear at runtime)
const GEAR_MAIN_PATH =
  "M131.726,75.823L141.91,77.253L141.91,82.747L131.726,84.177L129.564,92.246L137.669,98.576L134.922,103.334L125.387,99.48L119.48,105.387L123.334,114.922L118.576,117.669L112.246,109.564L104.177,111.726L102.747,121.91L97.253,121.91L95.823,111.726L87.754,109.564L81.424,117.669L76.666,114.922L80.52,105.387L74.613,99.48L65.078,103.334L62.331,98.576L70.436,92.246L68.274,84.177L58.09,82.747L58.09,77.253L68.274,75.823L70.436,67.754L62.331,61.424L65.078,56.666L74.613,60.52L80.52,54.613L76.666,45.078L81.424,42.331L87.754,50.436L95.823,48.274L97.253,38.09L102.747,38.09L104.177,48.274L112.246,50.436L118.576,42.331L123.334,45.078L119.48,54.613L125.387,60.52L134.922,56.666L137.669,61.424L129.564,67.754Z";

const GEAR_TL_PATH =
  "M69.654,38.488L77.875,39.452L77.875,44.548L69.654,45.512L66.966,52L72.098,58.494L68.494,62.098L62,56.966L55.512,59.654L54.548,67.875L49.452,67.875L48.488,59.654L42,56.966L35.506,62.098L31.902,58.494L37.034,52L34.346,45.512L26.125,44.548L26.125,39.452L34.346,38.488L37.034,32L31.902,25.506L35.506,21.902L42,27.034L48.488,24.346L49.452,16.125L54.548,16.125L55.512,24.346L62,27.034L68.494,21.902L72.098,25.506L66.966,32Z";

const GEAR_BR_PATH =
  "M167.693,111.879L173.894,112.844L173.894,117.156L167.693,118.121L165.304,123.889L169.006,128.957L165.957,132.006L160.889,128.304L155.121,130.693L154.156,136.894L149.844,136.894L148.879,130.693L143.111,128.304L138.043,132.006L134.994,128.957L138.696,123.889L136.307,118.121L130.106,117.156L130.106,112.844L136.307,111.879L138.696,106.111L134.994,101.043L138.043,97.994L143.111,101.696L148.879,99.307L149.844,93.106L154.156,93.106L155.121,99.307L160.889,101.696L165.957,97.994L169.006,101.043L165.304,106.111Z";

export function EngineeringIcon({ className }: EngineeringIconProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 200 160"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      {/* Main large gear - center */}
      <g className="eng-gear-main">
        <path
          d={GEAR_MAIN_PATH}
          fill="currentColor"
          fillOpacity="0.15"
          stroke="currentColor"
          strokeWidth="2"
        />
        <circle
          cx="100"
          cy="80"
          r="24"
          fill="currentColor"
          fillOpacity="0.05"
          stroke="currentColor"
          strokeWidth="1.5"
        />
        <circle
          cx="100"
          cy="80"
          r="10"
          fill="currentColor"
          fillOpacity="0.2"
          stroke="currentColor"
          strokeWidth="1.5"
        />
        {/* Spokes */}
        <line x1="112" y1="80" x2="122" y2="80" stroke="currentColor" strokeWidth="3" strokeOpacity="0.4" />
        <line x1="106" y1="90.392" x2="111" y2="99.053" stroke="currentColor" strokeWidth="3" strokeOpacity="0.4" />
        <line x1="94" y1="90.392" x2="89" y2="99.053" stroke="currentColor" strokeWidth="3" strokeOpacity="0.4" />
        <line x1="88" y1="80" x2="78" y2="80" stroke="currentColor" strokeWidth="3" strokeOpacity="0.4" />
        <line x1="94" y1="69.608" x2="89" y2="60.947" stroke="currentColor" strokeWidth="3" strokeOpacity="0.4" />
        <line x1="106" y1="69.608" x2="111" y2="60.947" stroke="currentColor" strokeWidth="3" strokeOpacity="0.4" />
      </g>

      {/* Top-left gear */}
      <g className="eng-gear-tl">
        <path
          d={GEAR_TL_PATH}
          fill="currentColor"
          fillOpacity="0.1"
          stroke="currentColor"
          strokeWidth="1.5"
        />
        <circle cx="52" cy="42" r="12" fill="currentColor" fillOpacity="0.05" stroke="currentColor" strokeWidth="1" />
        <circle cx="52" cy="42" r="5" fill="currentColor" fillOpacity="0.3" />
      </g>

      {/* Bottom-right gear */}
      <g className="eng-gear-br">
        <path
          d={GEAR_BR_PATH}
          fill="currentColor"
          fillOpacity="0.1"
          stroke="currentColor"
          strokeWidth="1.5"
        />
        <circle cx="152" cy="115" r="10" fill="currentColor" fillOpacity="0.05" stroke="currentColor" strokeWidth="1" />
        <circle cx="152" cy="115" r="4" fill="currentColor" fillOpacity="0.3" />
      </g>

      {/* Technical drawing - cross section view */}
      <g>
        <line
          x1="100"
          y1="25"
          x2="100"
          y2="135"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="4 2"
          strokeOpacity="0.3"
          className="eng-dash-v"
        />
        <line
          x1="30"
          y1="80"
          x2="170"
          y2="80"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="4 2"
          strokeOpacity="0.3"
          className="eng-dash-h"
        />
      </g>

      {/* Dimension arrows and measurements */}
      <g className="eng-dimension">
        <line x1="58" y1="20" x2="142" y2="20" stroke="currentColor" strokeWidth="1" strokeOpacity="0.5" />
        <path d="M58 20 L63 17 L63 23 Z" fill="currentColor" fillOpacity="0.5" />
        <path d="M142 20 L137 17 L137 23 Z" fill="currentColor" fillOpacity="0.5" />
        <line x1="100" y1="38" x2="100" y2="20" stroke="currentColor" strokeWidth="0.5" strokeOpacity="0.3" />
        <line x1="175" y1="42" x2="175" y2="115" stroke="currentColor" strokeWidth="1" strokeOpacity="0.5" />
        <path d="M175 42 L172 47 L178 47 Z" fill="currentColor" fillOpacity="0.5" />
        <path d="M175 115 L172 110 L178 110 Z" fill="currentColor" fillOpacity="0.5" />
      </g>

      {/* Connecting rods / linkages */}
      <g className="eng-rod">
        <line x1="72" y1="58" x2="68" y2="54" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeOpacity="0.3" />
        <line x1="128" y1="102" x2="136" y2="103" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeOpacity="0.3" />
      </g>

      {/* Piston on left side */}
      <g>
        <rect
          x="18"
          y="60"
          width="12"
          height="40"
          rx="2"
          fill="currentColor"
          fillOpacity="0.1"
          stroke="currentColor"
          strokeWidth="1"
        />
        <rect
          x="20"
          y="65"
          width="8"
          height="15"
          rx="1"
          fill="currentColor"
          fillOpacity="0.4"
          className="eng-piston"
        />
      </g>

      {/* Rotation indicators on main gear */}
      <circle cx="150" cy="80" r="2" fill="currentColor" className="eng-point-1" />
      <circle cx="100" cy="130" r="2" fill="currentColor" className="eng-point-2" />
      <circle cx="50" cy="80" r="2" fill="currentColor" className="eng-point-3" />
      <circle cx="100" cy="30" r="2" fill="currentColor" className="eng-point-4" />

      {/* Blueprint corner markers */}
      <g stroke="currentColor" strokeWidth="1.5" strokeOpacity="0.4">
        <path d="M15 20 L15 10 L25 10" fill="none" />
        <path d="M185 10 L195 10 L195 20" fill="none" />
        <path d="M15 140 L15 150 L25 150" fill="none" />
        <path d="M185 150 L195 150 L195 140" fill="none" />
      </g>

      {/* Scanning/verification line */}
      <line
        x1="30"
        y1="80"
        x2="30"
        y2="80"
        stroke="currentColor"
        strokeWidth="2"
        strokeOpacity="0.6"
        className="eng-scan"
      />
    </svg>
  );
}
